services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "9002:9002"
    environment:
      - SELENIUM_REMOTE_URL=http://selenium:4444/wd/hub
    command: python -m uvicorn main:app --host 0.0.0.0 --port 9002 
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      selenium:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9002/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    ports:
      - "9001:9001"
    command: python -m uvicorn main:app --host 0.0.0.0 --port 9001
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s 

  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    shm_size: 2g